### ISSUE TITLE
How stable is the t_cose adapter API expected to be?

### ISSUE THREAD

**Issue by raghuncstate** [laurencelundblade/t_cose#281]
Hello,

As you may know, for ARM CCA, the realm management monitor reference implementation, uses the t_cose library from here, to encode attestation tokens. As a part of enhancing the RMM to use a crypto adapter to do the attestation token signing, i chose to use the t_cose crypto adapter API to implement crypto operations to offload to a crypto engine.
The change can be seen here: https://review.trustedfirmware.org/c/TF-RMM/tf-rmm/+/29289.

As a part of review, some of the maintainers, are worried about the fact that t_cose library maintains it crypto adapters, for say mbedtls PSA, internally to the repository as opposed to externally, and are worried that the t_cose crypto adapter API may not be stable.

As a data point, i wanted to ask directly on the forum to see if you envisioned use case like the linked review, when using t_cose, and not using a pre-provided crypto adapter within the library.
I cannot think why this would NOT be envisioned since crypto adapter layers are abound for virtually all crypto libraries or other libraries that use crypto functionality.

Please let me know.

Thanks

**Comment by laurencelundblade** [comment]
I do envision use of crypto adaptors aside from those pre-provided. I consider the crypto adaptor layer kind of a public API and would only change it if there was no alternative.

The 1.0 branch is very stable. The dev/2.0 branch is likely to change, but for EC encryption, not hashing and signing.

I haven't tried it, but I think you can just not provide the EC encryption APIs. The t_cose library is constructed so that if you don't call any of the t_cose encryption features, the encryption code won't link and there's no need to link to encryption in the adaptor layer. The included tests of course do call the encryption features, but you could disable the encryption tests.

When t_cose 2.0 is further along the encryption adaptor layer should be come very stable.  Unfortunately the COSE encryption features are kind of a mess in the IETF and SUIT encryption has lost momentum. 

t_cose needs to have the pre-provided libraries bundled so it can work out of the box for most people.

Pretty much all the churn in the signing parts of the adaptor has come from Arm feature requests. But, I think the design for signing/verifying is now pretty solid.

That probably didn't answer all your questions, but many :-)

**Comment by laurencelundblade** [comment]
To add a little more, the sign/verify API was established 5 years ago. The only change was to add a context point to it. That happened two years ago. The context pointer is a general facility and makes it less likely to have to change the API in the future.
