### ISSUE TITLE
Check against several version of crypto libraries

### ISSUE THREAD

**Issue by laurencelundblade** [laurencelundblade/t_cose#53]
t_cose should be checked against popular released versions of mbedtls and openssl to be sure it is working with most, hopefully all, of them.

**Comment by letmaik** [comment]
I can help with that as an extension of the CI. Is that what you're looking for?

**Comment by letmaik** [comment]
Regarding the additional versions to test, for OpenSSL I don't think it makes sense to include 1.1.0 since it is EOL. So it would be 1.1.1 and 3.0. I would test 1.1.1 through Ubuntu 20.04 (already part of CI) and 3.0 through Ubuntu 22.04, instead of building it from source.

For MbedTLS, CI already has 2.28.0 and 3.1.0. Which other versions should be tested? 2.16.12 is the last release of the 2.16 LTS branch and was released December 2021. They advise folks to switch to 2.28 which is backward-compatible and maintained for another 3 years as LTS branch.

**Comment by laurencelundblade** [comment]
Agreed on OpenSSL 1.1.1 and 3.0 and the Mbed 2.28 and 3.1.0.

It's good to put in CI, but I'm also checking manually and with tdv. 

Turns out a lot of deprecating openssl functions are being used so I need to upgrade them a lot. So some works to do...

**Comment by laurencelundblade** [comment]
Fixed in #61
