### ISSUE TITLE
Support for EdDSA

### ISSUE THREAD

**Issue by dthaler** [laurencelundblade/t_cose#86]
The TEEP protocol wants to allow using EdDSA (value -8 in the COSE Algorithms registry) with COSE_Sign1

**Comment by plietar** [comment]
I've had a quick look into this, and it is unfortunately more complicated than it might seem.

The main challenge comes from the fact that, unlike other signature algorithms, EdDSA needs to be fed the entire `Sig_structure` (as defined in 4.4 of rfc8152), not just its hash. This means the structure needs to be present in memory at once, rather than computed incrementally [as it is done in t_cose today](https://github.com/laurencelundblade/t_cose/blob/d5ff4e282d8af34e5756627cf877ab399e7e51af/src/t_cose_util.c#L109-L181).

This is particularly difficult to do while avoiding memory allocations inside t_cose, especially when detached payloads are used.

(It also seems like MbedTLS doesn't even have an eddsa implementation: https://github.com/Mbed-TLS/mbedtls/pull/5819. Support in t_cose could be limited to the OpenSSL adapter of course).

**Comment by laurencelundblade** [comment]
A couple comments:

- t_cose 2.0 (the dev branch) has a different structure for integrating signature types and will line up better with what is needed here.
- The way I'd do this is to require the caller to supply the buffer needed. Some thing like t_cose_sign1_set_sigstruct_buffer(). Probably the caller can find the size, close enough by using the size calculation mode.
- t_cose 2.0, the dev branch in GitHub, has a different design that will line up better with integration of EdDSA without affecting the rest of the code.
- Probably most APIs for EdDSA use the same API they do for ECDSA which causes this problem, but do they have to? Is there something about EdDSA that forces this? Why can't they have an init()/update()/finish() API?

**Comment by plietar** [comment]
I haven’t delved deeper into the technical details of EdDSA, but it appears that PureEdDSA (the version that doesn’t use a hash) requires 2 passes over the data, hence a simple init/update/finish doesn’t work. I don’t know if a init/update/“re-init”/update/finish API is possible.

The EdDSA RFC suggests that payload can be pre-hashed in order to avoid the two passes (ie. what they call HashEdDSA), but that’s just not what COSE specifies.

**Comment by laurencelundblade** [comment]
OK. Thanks for updating on that. Makes sense.

One more thing --  t_cose 2.0 will not remove the need for t_cose_sign1_set_sigstruct_buffer() or such.

**Comment by plietar** [comment]
Thanks for the advice. I've got a quick prototype based on t_cose 1 using the suggested `set_sigstruct_buffer` function working, I should be able to open a PR within the next couple of days.

**Comment by laurencelundblade** [comment]
See #92.  Expecting to merge this in the next week or so.

**Comment by laurencelundblade** [comment]
Fixed by #92
